// src/data.js

export const categories = [
  "הכל",
  "שולחן השבת",
  "פסח",
  "לבית",
  "לגננות",
  "למלמד",
  "יוקרה",
];

export const productsData = [
  {
    id: 1,
    name: "סט פסח יוקרתי ",
    shortDesc: "דגם עלים זהב/כסף",
    longDesc: "סט פסח יוקרתי הכולל קערת הסדר מעוצבת והגדה מהודרת במעמד אקרילי",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_0001.jpg",
    fullImage: "public/img/IMG_0001.jpg",
    category: ["למלמד", "פסח", "יוקרה"],
  },
  {
    id: 2,
    name: "סט כלי הגשה שיש שחור",
    shortDesc: "מעוצב עם שוקולדים",
    longDesc: "קערה גדולה ובינונית + 2 קעריות קטנות לסלטים וכן סט מלח-פלפל",
    price: "₪280",
    thumbnail: "public/zip/IMG_0004.jpg",
    fullImage: "public/img/IMG_0004.jpg",
    category: [, "לגננות", "שולחן השבת"],
  },
  {
    id: 3,
    name: "סט הבדלה אקריליק",
    shortDesc: "אקרילי שקוף עם גימור זהב",
    longDesc:
      "סט מגש אקרילי עם סדר ההבדלה, מתקן לבשמים ולנר ההבדלה.",
    price: "₪120",
    thumbnail: "public/zip/IMG_0013.jpg",
    fullImage: "public/img/IMG_0013.jpg",
    category: ["לבית", "שולחן השבת"],
  },
  {
    id: 4,
    name: "כלי הגשה 4 חלקים",
    shortDesc: "דגם ענתיקה",
    longDesc: "2 יחידות מכל גודל, עם פס זהב + פרלינים ושוקולדים.",
    price: "₪150",
    thumbnail: "public/zip/IMG_0023.jpg",
    fullImage: "public/img/IMG_0023.jpg",
    category: ["לגננות", "שולחן השבת", "לבית"],
  },
  {
    id: 5,
    name: "שעון קיר גדול מעוצב",
    shortDesc: " עם מגוון שוקולדים",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_0046.jpg",
    fullImage: "public/img/IMG_0046.jpg",
    category: ["לגננות", "למלמד", "לבית"],
  },
  {
    id: 6,
    name: "בקבוק יין זכוכית + 6 כוסיות",
    shortDesc: "מרשים, זול וטעים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_0048.jpg",
    fullImage: "public/img/IMG_0048.jpg",
    category: ["פסח", "למלמד", "שולחן השבת"],
  },
  {
    id: 7,
    name: "כד וכוסות מרשים",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1374.jpg",
    fullImage: "public/img/IMG_1374.jpg",
    category: ["לבית", "לגננות", "פסח", "שולחן השבת"],
  },
  {
    id: 8,
    name: "סט ברכונים ומעין שלוש אקרילי",
    shortDesc: "רחיץ, בגימור זהב",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1361.jpg",
    fullImage: "public/img/IMG_1361.jpg",
    category: ["למלמד", "שולחן השבת", "לגננות"],
  },
  {
    id: 9,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1368.jpg",
    fullImage: "public/img/IMG_1368.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 10,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_0050.jpg",
    fullImage: "public/img/IMG_0050.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 11,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1376.jpg",
    fullImage: "public/img/IMG_1376.jpg",
    category: ["לבית"],
  },
  {
    id: 12,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1377.jpg",
    fullImage: "public/img/IMG_1377.jpg",
    category: ["מארזים", "יוקרה"],
  },
  {
    id: 13,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1378.jpg",
    fullImage: "public/img/IMG_1378.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 14,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_1381.jpg",
    fullImage: "public/img/IMG_1381.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 15,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1384.jpg",
    fullImage: "public/img/IMG_1384.jpg",
    category: ["לבית"],
  },
  {
    id: 16,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1386.jpg",
    fullImage: "public/img/IMG_1386.jpg",
    category: ["מארזים", "יוקרה"],
  },
  {
    id: 17,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1387.jpg",
    fullImage: "public/img/IMG_1387.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 18,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_1391.jpg",
    fullImage: "public/img/IMG_1391.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 19,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1398.jpg",
    fullImage: "public/img/IMG_1398.jpg",
    category: ["לבית"],
  },
  {
    id: 20,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1400.jpg",
    fullImage: "public/img/IMG_1400.jpg",
    category: ["מארזים", "יוקרה"],
  },
  {
    id: 21,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1403.jpg",
    fullImage: "public/img/IMG_1403.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 22,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_1406.jpg",
    fullImage: "public/img/IMG_1406.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 23,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1407.jpg",
    fullImage: "public/img/IMG_1407.jpg",
    category: ["לבית"],
  },
  {
    id: 24,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1417.jpg",
    fullImage: "public/img/IMG_1417.jpg",
    category: ["מארזים", "יוקרה"],
  },
  {
    id: 25,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1421.jpg",
    fullImage: "public/img/IMG_1421.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 26,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_1423.jpg",
    fullImage: "public/img/IMG_1423.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 27,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1426.jpg",
    fullImage: "public/img/IMG_1426.jpg",
    category: ["לבית"],
  },
  {
    id: 28,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_1430.jpg",
    fullImage: "public/img/IMG_1430.jpg",
    category: ["מארזים", "יוקרה"],
  },
  {
    id: 29,
    name: "מעמד ",
    shortDesc: " אקריליק",
    longDesc:
      "שעון יד מעוצב עם רצועת עור איכותית, עמיד במים ומתאים לאירועים רשמיים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "480 ₪",
    thumbnail: "public/zip/IMG_1435.jpg",
    fullImage: "public/img/IMG_1435.jpg",
    category: ["קודש", "שולחן שבת"],
  },
  {
    id: 30,
    name: "סט טיפוח לאישה",
    shortDesc: "מארז מפנק של שמנים וקרמים",
    longDesc:
      "מארז מתנה מושלם הכולל קרם גוף, שמן רחצה ונר ריחני. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪280",
    thumbnail: "public/zip/IMG_1440.jpg",
    fullImage: "public/img/IMG_1440.jpg",
    category: ["נשים", "מארזים"],
  },
  {
    id: 31,
    name: "מנורת לילה מעוצבת",
    shortDesc: "מנורת אווירה לבית",
    longDesc:
      "מנורת לילה בעיצוב מודרני המפיצה אור רך ונעים. לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית.",
    price: "₪120",
    thumbnail: "public/zip/IMG_1441.jpg",
    fullImage: "public/img/IMG_1441.jpg",
    category: ["לבית"],
  },
  {
    id: 32,
    name: "מארז שוקולד פרימיום",
    shortDesc: "שוקולד בלגי בעבודת יד",
    longDesc: "מארז של 24 פרלינים בטעמים משתנים. מתנה מושלמת לכל אירוע.",
    price: "₪150",
    thumbnail: "public/zip/IMG_9888.jpg",
    fullImage: "public/img/IMG_9888.jpg",
    category: ["מארזים", "יוקרה"],
  },
];

export const herofullImages = [
  "public/img/IMG_0028.JPG",
  // "public/img/IMG_0014.JPG",
  "public/img/unnamed.webp",
];
